#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Wheel1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Wheel2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Wheel3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Wheel4,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    W2Servo,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    W1Servo,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    W3Servo,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    W4Servo,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
			servo[W2Servo] = 235;
			servo[W1Servo] = 15;
			servo[W3Servo] = 15;
			servo[W4Servo] = 250;
	}



}
